### ISSUE TITLE
Installed peers get to package.json in "dependencies" section when using npm 5

### ISSUE THREAD

**Issue by jehy** [spatie/npm-install-peers#13]
Installed peers get to package.json in "dependencies" section when using npm 5. This is likely related to npm 5 adding to "dependencies" even without "save" flag.

This can ve avoided with setting flag `npm config set save false` cbut setting this for user environment is wrong.

Also seems that we can use `--no-save` flag, I am gonna test it.

UPD. Looks fine, added a PR.

**Comment by jehy** [comment]
It is possible that I spelled option wrong, if so - check https://github.com/marapper/npm-install-peers/commit/07fc6a648ebf790d265c3abd16bb9dfa568d233a

**Comment by sschuberth** [comment]
Isn't this very related to my issue #12?

**Comment by sebastiandedeyne** [comment]
`1.2.0-rc.1` should fix this. Could anyone give it a spin?

**Comment by alexindigo** [comment]
It's because of this line: https://github.com/spatie/npm-install-peers/blob/master/src/index.js#L33

There is no `no-save` option in npm, `--no-save` argument is translated into `save: false` option.

**Comment by MarkChrisLevy** [comment]
@sebastiandedeyne In 1.2.0-rc.1 this is not fixed. As @alexindigo noted, there should be "--no-save" argument, not "no-save".

**Comment by alexindigo** [comment]
@mmlleevvyy Checkout npmjs.org/install-peers it has that issue fixed and automates things a little bit further :)

**Comment by sebastiandedeyne** [comment]
Released `1.2.0-rc.2` with a fix for the `--no-save` argument.

**Comment by alexindigo** [comment]
I think it works a little bit different from what your fix implies.
`--no-save` is parsed from cli args into `options['save'] = false`.

**Comment by sebastiandedeyne** [comment]
Published another go

**Comment by alexindigo** [comment]
Looks good 👍

**Comment by sebastiandedeyne** [comment]
Stable version `1.2.0` has been released
